// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddStory: typeof import('C:/Coding/timelino/src/components/AddStory.vue')['default']
    Badge: typeof import('C:/Coding/timelino/src/components/Badge.vue')['default']
    ColorPicker: typeof import('C:/Coding/timelino/src/components/ColorPicker.vue')['default']
    'IMdi:account': typeof import('~icons/mdi/account')['default']
    'IMdi:arrowDownThick': typeof import('~icons/mdi/arrow-down-thick')['default']
    'IMdi:bell': typeof import('~icons/mdi/bell')['default']
    'IMdi:clock': typeof import('~icons/mdi/clock')['default']
    'IMdi:cog': typeof import('~icons/mdi/cog')['default']
    'IMdi:filterOff': typeof import('~icons/mdi/filter-off')['default']
    'IMdi:google': typeof import('~icons/mdi/google')['default']
    'IMdi:image': typeof import('~icons/mdi/image')['default']
    'IMdi:logoutVariant': typeof import('~icons/mdi/logout-variant')['default']
    'IMdi:minus': typeof import('~icons/mdi/minus')['default']
    'IMdi:plus': typeof import('~icons/mdi/plus')['default']
    'IMdi:squareEditOutline': typeof import('~icons/mdi/square-edit-outline')['default']
    'IMdi:trashCanOutline': typeof import('~icons/mdi/trash-can-outline')['default']
    'IMdi:twitter': typeof import('~icons/mdi/twitter')['default']
    Modal: typeof import('C:/Coding/timelino/src/components/Modal.vue')['default']
    ModalDelete: typeof import('C:/Coding/timelino/src/components/ModalDelete.vue')['default']
    'ModalDelete copy': typeof import('C:/Coding/timelino/src/components/ModalDelete copy.vue')['default']
    ModalDiscard: typeof import('C:/Coding/timelino/src/components/ModalDiscard.vue')['default']
    ModalStory: typeof import('C:/Coding/timelino/src/components/ModalStory.vue')['default']
    'ModalStory copy': typeof import('C:/Coding/timelino/src/components/ModalStory copy.vue')['default']
    Notification: typeof import('C:/Coding/timelino/src/components/Notification.vue')['default']
    'Notification copy': typeof import('C:/Coding/timelino/src/components/Notification copy.vue')['default']
    Profile: typeof import('C:/Coding/timelino/src/components/Profile.vue')['default']
    ProfileDropdown: typeof import('C:/Coding/timelino/src/components/ProfileDropdown.vue')['default']
    TestQuillContent: typeof import('C:/Coding/timelino/src/components/TestQuillContent.vue')['default']
    TestQuillEditor: typeof import('C:/Coding/timelino/src/components/TestQuillEditor.vue')['default']
  }
}

export { }
